BaseDirectory = "/opt/homekit-garage-shutter"

EnableHomekitLockSwitch     = true
EnableHomekitLockMechanism  = true
EnableHomekitContactSensors = true
LockWhenClosed              = true
CloseWhenLocked             = true

Name         = "Garage Shutter"
Manufacturer = ""
Model        = ""
SerialNumber = ""

HomekitPinCode = "00001234"

OpenButtonRelay   = 1
CloseButtonRelay  = 3
OpenContactInput  = 1
CloseContactInput = 2