### App configuration ###
#

# Base directory where Homekit data will be stored
BaseDirectory = "/opt/homekit-garage-shutter"

# Enable a switch to prevent the shutter from being opened when the switch is
# on. The shutter can always be closed even when the switch is on.
# This switch can be used in automations unlik the lock mechanism which will
# prompt for user input.
EnableHomekitLockSwitch = true

# Enable a lock mechanism to prevent the shutter from being opened when locked.
# The shutter can always be closed even when locked.
EnableHomekitLockMechanism = true

# Enable a contact sensor for the shutter closed state
EnableHomekitContactSensor = true

# Automatically lock the shutter whenever it is closed
LockWhenClosed = true

# Automatically close the shutter whenever it is locked
CloseWhenLocked = true

# The length of time in milliseconds that the switch buttons are pressed.
SwitchHoldMs = 500


### Apple Homekit configuartion ###
#

# Tha name of the bridge and accessories that will be presented to Homekit
Name = "Garage Shutter"

# The manufacturer of the shutter
Manufacturer = ""

# The model number of the shutter
Model = ""

# The serial number of the shutter
SerialNumber = ""

# The pin code used to pair with Homekit. This must be a 8 digit number
# and should be unique to the device.
HomekitPinCode = "00001234"


### Pimoroni Autommation HAT configuration ###
#
# Garage shutter remote controls that have only a single button can use a
# Pimoroni Automation HAT Mini. Simply set the open and close relay numbers
# to 3.

# The relay number connected to the open button
OpenButtonRelay = 1

# The relay number connected to the close button
CloseButtonRelay = 3

# The input number connected to the open contact sensor
OpenContactInput = 1

# The input number connected to the close contact sensor
CloseContactInput = 2